<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class SeedOrientadoresExternosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('orientadores')->insert(['CPF' => '34106176807', 'nome'=> ucwords(strtolower('ADILSON KLEBER FERREIRA')), 'email'=>'ferreira_kleber@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('34106176807',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '35648939892', 'nome'=> ucwords(strtolower('ADRIANE LOPES MEDEIROS SIMONE')), 'email'=>'almedeiros@usp.br','instituicao_vinculo'=>'FSP', 'password'=> password_hash(substr('35648939892',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '23400626830', 'nome'=> ucwords(strtolower('ALESSANDRA PONTILLO')), 'email'=>'alepontillo@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('23400626830',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '22064625836', 'nome'=> ucwords(strtolower('ALEXANDER HENNING ULRICH')), 'email'=>'henning@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('22064625836',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '29100890880', 'nome'=> ucwords(strtolower('ALICE CRISTINA RODRIGUES')), 'email'=>'alice-rodrigues@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('29100890880',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '13767450895', 'nome'=> ucwords(strtolower('ALICIA JULIANA KOWALTOWSKI')), 'email'=>'alicia@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('13767450895',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '03303595925', 'nome'=> ucwords(strtolower('ALINE SORIANO LOPES')), 'email'=>'alinedqi@hotmail.com','instituicao_vinculo'=>'UNIFESP', 'password'=> password_hash(substr('03303595925',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '63379082600', 'nome'=> ucwords(strtolower('ALTACÍLIO APARECIDO NUNES')), 'email'=>'altacilio@fmrp.usp.br','instituicao_vinculo'=>'FMRP', 'password'=> password_hash(substr('63379082600',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '07487350894', 'nome'=> ucwords(strtolower('ALTAMIR BENEDITO DE SOUSA')), 'email'=>'absousa2004@yahoo.com.br','instituicao_vinculo'=>'HU', 'password'=> password_hash(substr('07487350894',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '70335710891', 'nome'=> ucwords(strtolower('ANA MARIA CARMONA RIBEIRO')), 'email'=>'mcribeir@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('70335710891',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '25225431801', 'nome'=> ucwords(strtolower('ANA PAULA LEPIQUE')), 'email'=>'analepique@yahoo.com','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('25225431801',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '13671180854', 'nome'=> ucwords(strtolower('ANDRÉA DA SILVA TORRÃO')), 'email'=>'andrea@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('13671180854',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '65726448804', 'nome'=> ucwords(strtolower('ANGELO RAFAEL CARPINELLI')), 'email'=>'angelo@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('65726448804',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '27281213891', 'nome'=> ucwords(strtolower('ANTONIA TAVARES DO AMARAL')), 'email'=>'atdamara@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('27281213891',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '19940386834', 'nome'=> ucwords(strtolower('ANTONIO CARLOS PEREIRA BARRETTO')), 'email'=>'antonio.barretto@incor.usp.br','instituicao_vinculo'=>'FM', 'password'=> password_hash(substr('19940386834',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '04380206858', 'nome'=> ucwords(strtolower('AQUILAS NOGUEIRA MENDES')), 'email'=>'aquilasm@uol.com.br','instituicao_vinculo'=>'FSP', 'password'=> password_hash(substr('04380206858',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '28716563808', 'nome'=> ucwords(strtolower('ARIADINY DE LIMA CAETANO')), 'email'=>'ariadiny.caetano@fcmsantacasasp.edu.br','instituicao_vinculo'=>'Santa Casa SP', 'password'=> password_hash(substr('28716563808',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '00166281875', 'nome'=> ucwords(strtolower('BALMES VEGA GARCIA')), 'email'=>'balmes@usp.br','instituicao_vinculo'=>'FD', 'password'=> password_hash(substr('00166281875',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '32611822883', 'nome'=> ucwords(strtolower('BARBARA FALQUETTO')), 'email'=>'barbaraf@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('32611822883',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '04955684815', 'nome'=> ucwords(strtolower('BAYARDO BAPTISTA TORRES')), 'email'=>'bayardo@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('04955684815',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '68619049887', 'nome'=> ucwords(strtolower('BERENICE BILHARINHO DE MENDONÇA')), 'email'=>'beremen@usp.br','instituicao_vinculo'=>'FM', 'password'=> password_hash(substr('68619049887',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '11304384810', 'nome'=> ucwords(strtolower('BRENO PANNIA ESPÓSITO')), 'email'=>'breno@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('11304384810',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '11615160779', 'nome'=> ucwords(strtolower('CAMILA AREIAS DE OLIVEIRA')), 'email'=>'milaareias@usp.br','instituicao_vinculo'=>'Universidade Federal do ABC', 'password'=> password_hash(substr('11615160779',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '05007840866', 'nome'=> ucwords(strtolower('CARLA COLUMBANO DE OLIVEIRA')), 'email'=>'ccoliv@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('05007840866',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '10209636890', 'nome'=> ucwords(strtolower('CARLA ROBERTA OLIVEIRA CARVALHO ')), 'email'=>'croc@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('10209636890',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '18272138840', 'nome'=> ucwords(strtolower('CARLA TADDEI DE CASTRO NEVES')), 'email'=>'crtaddei@usp.br','instituicao_vinculo'=>'EACH', 'password'=> password_hash(substr('18272138840',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '22278587889', 'nome'=> ucwords(strtolower('CAROLINA BELTRAME DEL DEBBIO')), 'email'=>'carol.deldebbio@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('22278587889',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '05216321616', 'nome'=> ucwords(strtolower('CAROLINA CAMPOLINA REBELLO HORTA')), 'email'=>'carolinacampolina@yahoo.com.br','instituicao_vinculo'=>'Centro Universitário de Sete Lagoas', 'password'=> password_hash(substr('05216321616',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '25785078805', 'nome'=> ucwords(strtolower('CAROLINA DEMARCHI MUNHOZ')), 'email'=>'cdmunhoz@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('25785078805',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '13647136832', 'nome'=> ucwords(strtolower('CINTIA FRIDMAN RAVE')), 'email'=>'cfridman@usp.br','instituicao_vinculo'=>'FM', 'password'=> password_hash(substr('13647136832',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '19263931801', 'nome'=> ucwords(strtolower('CLÁUDIA ROSSO FELIPE')), 'email'=>'claudiafelipe@nefro.epm.br','instituicao_vinculo'=>'UNIFESP', 'password'=> password_hash(substr('19263931801',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '05866119838', 'nome'=> ucwords(strtolower('CLAUDIMIR LUCIO DO LAGO')), 'email'=>'claudemi@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('05866119838',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '08986179873', 'nome'=> ucwords(strtolower('CLAUDIO ROMERO FARIAS MARINHO')), 'email'=>'marinho@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('08986179873',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '31189092859', 'nome'=> ucwords(strtolower('CRISTIANE RODRIGUES GUZZO CARVALHO')), 'email'=>'crisguzzo@gmail.com','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('31189092859',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '00383028884', 'nome'=> ucwords(strtolower('CRISTÓFORO SCAVONE')), 'email'=>'cristoforo.scavone@gmail.com','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('00383028884',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        //DB::table('orientadores')->insert(['CPF' => '31539943828', 'nome'=> ucwords(strtolower('DANIEL PECORARO DEMARQUE ')), 'email'=>'danieldemarque@usp.br','instituicao_vinculo'=>'FCF', 'password'=> password_hash(substr('31539943828',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '30342151851', 'nome'=> ucwords(strtolower('DANIELA OLIVEIRA DE MELO')), 'email'=>'Melo.daniela@unifesp.br','instituicao_vinculo'=>'UNIFESP', 'password'=> password_hash(substr('30342151851',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '90825870844', 'nome'=> ucwords(strtolower('DENISE CAVALLINI CYRILLO')), 'email'=>'dccyrill@usp.br','instituicao_vinculo'=>'FEA', 'password'=> password_hash(substr('90825870844',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '30226177807', 'nome'=> ucwords(strtolower('DENISE MORAIS DA FONSECA')), 'email'=>'denisefonseca@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('30226177807',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '06410373929', 'nome'=> ucwords(strtolower('DENIZE CRISTINA FAVARO')), 'email'=>'favarodenize@gmail.com','instituicao_vinculo'=>'UFMG', 'password'=> password_hash(substr('06410373929',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '27319535866', 'nome'=> ucwords(strtolower('ELISA MITIKO KAWAMOTO')), 'email'=>'kawamotoe@gmail.com','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('27319535866',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '75505266800', 'nome'=> ucwords(strtolower('ESTELA MARIS ANDRADE FORELL BEVILACQUA')), 'email'=>'bevilacq@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('75505266800',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '05432607808', 'nome'=> ucwords(strtolower('FABIO LUIZ NAVARRO MARQUES')), 'email'=>'fabio.marques@hc.fmusp.br','instituicao_vinculo'=>'FM', 'password'=> password_hash(substr('05432607808',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '00604705930', 'nome'=> ucwords(strtolower('FERNANDA MARQUES DA CUNHA')), 'email'=>'fmcunha@usp.br','instituicao_vinculo'=>'EACH', 'password'=> password_hash(substr('00604705930',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '16691795830', 'nome'=> ucwords(strtolower('FERNANDO MUSSA ABUJAMRA AITH')), 'email'=>'fernando.aith@usp.br','instituicao_vinculo'=>'FM', 'password'=> password_hash(substr('16691795830',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '19270999866', 'nome'=> ucwords(strtolower('FERNANDO SILVA LOPES')), 'email'=>'fslopes@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('19270999866',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '16358232851', 'nome'=> ucwords(strtolower('FLÁVIA MORI SARTI')), 'email'=>'flamori@usp.br','instituicao_vinculo'=>'EACH', 'password'=> password_hash(substr('16358232851',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '10675125863', 'nome'=> ucwords(strtolower('GABRIEL PADILLA MALDONADO')), 'email'=>'gpadilla@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('10675125863',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '11796772852', 'nome'=> ucwords(strtolower('GERALDO SANTANA MAGALHÃES')), 'email'=>'gsmaga@butantan.gov.br','instituicao_vinculo'=>'Butantã', 'password'=> password_hash(substr('11796772852',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '70498888185', 'nome'=> ucwords(strtolower('GIUSEPPE PALMISANO')), 'email'=>'palmisano.gp@gmail.com','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('70498888185',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '12498862790', 'nome'=> ucwords(strtolower('GLAUCIO MONTEIRO FERREIRA')), 'email'=>'gmf@usp.br','instituicao_vinculo'=>'FBC/FCF', 'password'=> password_hash(substr('12498862790',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '00438342992', 'nome'=> ucwords(strtolower('GRAZIELLA ELIZA RONSEIN')), 'email'=>'ronsein@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('00438342992',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '67741770853', 'nome'=> ucwords(strtolower('IOLANDA MIDEA CUCCOVIA')), 'email'=>'imcuccov@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('67741770853',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '15763321871', 'nome'=> ucwords(strtolower('ISAIAS GLEZER')), 'email'=>'iglezer@unifesp.br','instituicao_vinculo'=>'UNIFESP', 'password'=> password_hash(substr('15763321871',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '02488437964', 'nome'=> ucwords(strtolower('JEAN PIERRE SCHATZMANN PERON')), 'email'=>'jeanpierre@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('02488437964',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '35015715854', 'nome'=> ucwords(strtolower('JOÃO AGOSTINHO MACHADO NETO')), 'email'=>'jamachadoneto@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('35015715854',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '36866015839', 'nome'=> ucwords(strtolower('JOÃO FIGUEIREDO NOBRE CORTESE')), 'email'=>'Joao.cortese@usp.br','instituicao_vinculo'=>'IB', 'password'=> password_hash(substr('36866015839',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '08334141866', 'nome'=> ucwords(strtolower('JOÃO GUSTAVO PESSINI AMARANTE MENDES')), 'email'=>'gpam@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('08334141866',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '23661094823', 'nome'=> ucwords(strtolower('JOÃO HENRIQUE PICADO MADALENA SANTOS')), 'email'=>'jhpmsantos@gmail.com','instituicao_vinculo'=>'FCF', 'password'=> password_hash(substr('23661094823',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '21688150897', 'nome'=> ucwords(strtolower('JOÃO PALERMO NETO')), 'email'=>'jpalermo@usp.br','instituicao_vinculo'=>'FMVZ', 'password'=> password_hash(substr('21688150897',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '03073323813', 'nome'=> ucwords(strtolower('JONAS GRUBER')), 'email'=>'jogruber@usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('03073323813',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '06587726860', 'nome'=> ucwords(strtolower('JOSÉ GREGÓRIO CABRERA GOMEZ')), 'email'=>'jgcgomez@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('06587726860',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '10690802765', 'nome'=> ucwords(strtolower('JOSIANE SOUZA PEREIRA DANIEL')), 'email'=>'josianedaniel@usp.br','instituicao_vinculo'=>'FCF', 'password'=> password_hash(substr('10690802765',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '22731420804', 'nome'=> ucwords(strtolower('KAREN DE MORAIS ZANI')), 'email'=>'karen.zani@butantan.gov.br','instituicao_vinculo'=>'Butantan', 'password'=> password_hash(substr('22731420804',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '03455638910', 'nome'=> ucwords(strtolower('KELLY ISHIDA')), 'email'=>'ishidakelly@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('03455638910',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '13451690861', 'nome'=> ucwords(strtolower('LARA MENDES DE ALMEIDA')), 'email'=>'larameal@usp.br','instituicao_vinculo'=>'FBC/FCF', 'password'=> password_hash(substr('13451690861',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '31179682882', 'nome'=> ucwords(strtolower('LEONARDO SANTANA NOVAES')), 'email'=>'leonardosnovaes@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('31179682882',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '08964682831', 'nome'=> ucwords(strtolower('LUCIA ROSSETTI LOPES')), 'email'=>'llopes@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('08964682831',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '24805867825', 'nome'=> ucwords(strtolower('LUCIANA BIAGINI LOPES')), 'email'=>'lublopes@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('24805867825',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '01990877761', 'nome'=> ucwords(strtolower('LUCIANA VENTURINI ROSSONI')), 'email'=>'lrossoni@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('01990877761',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '16421695876', 'nome'=> ucwords(strtolower('LUCIANE MARZZULLO CICARELLI')), 'email'=>'lucianemc@usp.br','instituicao_vinculo'=>'HU', 'password'=> password_hash(substr('16421695876',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '09082264897', 'nome'=> ucwords(strtolower('LUIS EDUARDO SOARES NETTO')), 'email'=>'nettoles@ib.usp.br','instituicao_vinculo'=>'IB', 'password'=> password_hash(substr('09082264897',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '11290312842', 'nome'=> ucwords(strtolower('LUIZ ALEXANDRE KULAY')), 'email'=>'Luiz.kulay@usp.br','instituicao_vinculo'=>'POLI', 'password'=> password_hash(substr('11290312842',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '30055972888', 'nome'=> ucwords(strtolower('MAÍRA MARTINS DE SOUZA GODOY SIMÕES')), 'email'=>'msimoes5@its.jnj.com','instituicao_vinculo'=>'Johnson & Johnson', 'password'=> password_hash(substr('30055972888',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '18521791801', 'nome'=> ucwords(strtolower('MARCELO FILONZI DOS SANTOS')), 'email'=>'filonzi@usp.br','instituicao_vinculo'=>'FBC/FCF', 'password'=> password_hash(substr('18521791801',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '08322641800', 'nome'=> ucwords(strtolower('MARCELO URBANO FERREIRA')), 'email'=>'muferrei@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('08322641800',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '10210846895', 'nome'=> ucwords(strtolower('MARGARETH MIE NAKAMURA MATSUDA')), 'email'=>'mmatsuda@ipen.br','instituicao_vinculo'=>'IPEN', 'password'=> password_hash(substr('10210846895',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '01857019814', 'nome'=> ucwords(strtolower('MARIA APARECIDA NICOLETTI')), 'email'=>'nicoletti@usp.br','instituicao_vinculo'=>'UNG / USP', 'password'=> password_hash(substr('01857019814',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '38398936827', 'nome'=> ucwords(strtolower('MARIA GABRIELA BERZOTI COELHO')), 'email'=>'gabrielaberzoti@gmail.com','instituicao_vinculo'=>'Butantã', 'password'=> password_hash(substr('38398936827',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '02264750855', 'nome'=> ucwords(strtolower('MARIA LUCIA ZAIDAN DAGLI')), 'email'=>'mlzdagli@usp.br','instituicao_vinculo'=>'FMVZ', 'password'=> password_hash(substr('02264750855',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '26711366840', 'nome'=> ucwords(strtolower('MARILENE HOHMUTH LOPES')), 'email'=>'marilenehl@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('26711366840',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '38418125896', 'nome'=> ucwords(strtolower('MARILIA BERLOFA VISACRI')), 'email'=>'mvisacri@unicamp.br','instituicao_vinculo'=>'UNICAMP', 'password'=> password_hash(substr('38418125896',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '03566729809', 'nome'=> ucwords(strtolower('MARILIA CRISTINA PRADO LOUVISON')), 'email'=>'mariliacpl@usp.br','instituicao_vinculo'=>'FSP', 'password'=> password_hash(substr('03566729809',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '00492526826', 'nome'=> ucwords(strtolower('MARINA FRANCO MAGGI TAVARES')), 'email'=>'mfmtavar@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('00492526826',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '57519889815', 'nome'=> ucwords(strtolower('MARTHA MASSAKO TANIZAKI')), 'email'=>'martha.tanizaki@butantan.gov.br','instituicao_vinculo'=>'Butantã', 'password'=> password_hash(substr('57519889815',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '31944075895', 'nome'=> ucwords(strtolower('MAURO CÉSAR CAFUNDÓ DE MORAIS')), 'email'=>'mauro_morais@usp.br','instituicao_vinculo'=>'FBC', 'password'=> password_hash(substr('31944075895',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '26880163858', 'nome'=> ucwords(strtolower('MERARI DE FÁTIMA RAMIRES FERRARI')), 'email'=>'merari@usp.br','instituicao_vinculo'=>'IB', 'password'=> password_hash(substr('26880163858',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '25219269810', 'nome'=> ucwords(strtolower('MICHELE GEORGES ISSA')), 'email'=>'michelegeorges@usp.br','instituicao_vinculo'=>'FCF', 'password'=> password_hash(substr('25219269810',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '30595822894', 'nome'=> ucwords(strtolower('MILENE CRISTINA MENEZES DOS SANTOS')), 'email'=>'menezes.millene@gmail.com','instituicao_vinculo'=>'Butantã ', 'password'=> password_hash(substr('30595822894',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '13767111845', 'nome'=> ucwords(strtolower('NADJA CRISTHINA DE SOUZA PINTO')), 'email'=>'nadja@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('13767111845',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '06984449650', 'nome'=> ucwords(strtolower('NAYARA BEGALLI SCALCO VIEIRA')), 'email'=>'nayara.scalco@isaude.sp.gov.br','instituicao_vinculo'=>'Secret. Est. da Saúde', 'password'=> password_hash(substr('06984449650',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '03872348884', 'nome'=> ucwords(strtolower('NEWTON SABINO CANTERAS')), 'email'=>'newton@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('03872348884',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '04140703806', 'nome'=> ucwords(strtolower('NICOLINA SILVANA ROMANO LIEBER')), 'email'=>'nicolina@usp.br','instituicao_vinculo'=>'FSP', 'password'=> password_hash(substr('04140703806',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '35881860349', 'nome'=> ucwords(strtolower('NIELS OLSEN SARAIVA CAMARA')), 'email'=>'niels@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('35881860349',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '21505841828', 'nome'=> ucwords(strtolower('Nilton Erbet Lincopan Huenuman')), 'email'=>'lincopan@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('21505841828',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '00767790928', 'nome'=> ucwords(strtolower('OTAVIO CABRAL MARQUES')), 'email'=>'otavio.cmarques@gmail.com','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('00767790928',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '21256611875', 'nome'=> ucwords(strtolower('PAOLO DI MASCIO')), 'email'=>'pdmascio@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('21256611875',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '12680335880', 'nome'=> ucwords(strtolower('PATRICIA GAMA')), 'email'=>'patgama@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('12680335880',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '06256891864', 'nome'=> ucwords(strtolower('PATRICIA MARIA BERARDO GONÇALVES MAIA CAMPOS')), 'email'=>'pmcampos@usp.br','instituicao_vinculo'=>'FCFRP', 'password'=> password_hash(substr('06256891864',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        //DB::table('orientadores')->insert(['CPF' => '00672723557', 'nome'=> ucwords(strtolower('PATRICIA MELO AGUIAR')), 'email'=>'aguiar.pm@usp.br','instituicao_vinculo'=>'FCF', 'password'=> password_hash(substr('00672723557',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '03165291845', 'nome'=> ucwords(strtolower('PAULO LEE HO')), 'email'=>'paulo.ho@butantan.gov.br','instituicao_vinculo'=>'Butantã', 'password'=> password_hash(substr('03165291845',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '49042882034', 'nome'=> ucwords(strtolower('PAULO ROBERTO HRIHOROWITSCH MORENO')), 'email'=>'prmoreno@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('49042882034',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '39747729873', 'nome'=> ucwords(strtolower('PAULO VICTOR CUESTA CALVO')), 'email'=>'pvccalvo@usp.br','instituicao_vinculo'=>'FBT - FCF', 'password'=> password_hash(substr('39747729873',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '22399953860', 'nome'=> ucwords(strtolower('PEDRO AUGUSTO CARLOS MAGNO FERNANDES')), 'email'=>'pacmf@usp.br','instituicao_vinculo'=>'IB', 'password'=> password_hash(substr('22399953860',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '11275429823', 'nome'=> ucwords(strtolower('RAUL DIAS DOS SANTOS FILHO')), 'email'=>'Raul.santos@incor.usp.br','instituicao_vinculo'=>'FMUSP', 'password'=> password_hash(substr('11275429823',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '24851890800', 'nome'=> ucwords(strtolower('RENATO HEIDOR')), 'email'=>'rheidor@usp.br','instituicao_vinculo'=>'FCF', 'password'=> password_hash(substr('24851890800',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '01310624330', 'nome'=> ucwords(strtolower('RENATO SIMÕES GASPAR')), 'email'=>'renatosgaspar@gmail.com','instituicao_vinculo'=>'FMUSP', 'password'=> password_hash(substr('01310624330',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '08729157862', 'nome'=> ucwords(strtolower('RICARDO JOSÉ GIORDANO')), 'email'=>'giordano@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('08729157862',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '82154473091', 'nome'=> ucwords(strtolower('ROBERTA LOPES DREKENER')), 'email'=>'Roberta.drekener@gmail.com','instituicao_vinculo'=>'Integra Pharmaceutical Consultancy LTDA', 'password'=> password_hash(substr('82154473091',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '36830570840', 'nome'=> ucwords(strtolower('RODOLFO FERREIRA MARQUES')), 'email'=>'rodolfofmarques@hotmail.com','instituicao_vinculo'=>'Univ.Estácio de Sá', 'password'=> password_hash(substr('36830570840',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '09123689854', 'nome'=> ucwords(strtolower('ROSANA CAMARINI')), 'email'=>'camarini@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('09123689854',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '39044300920', 'nome'=> ucwords(strtolower('RUI CURI')), 'email'=>'ruicuri@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('39044300920',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '15667680807', 'nome'=> ucwords(strtolower('SAYURI MIYAMOTO')), 'email'=>'miyamoto@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('15667680807',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '34730664787', 'nome'=> ucwords(strtolower('SÉRGIO VERJOVSKI ALMEIDA')), 'email'=>'verjo@iq.usp.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('34730664787',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '18200588831', 'nome'=> ucwords(strtolower('SILVANA AUXILIADORA BORDIN DA SILVA')), 'email'=>'silvana.bordin@gmail.com','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('18200588831',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '07964525808', 'nome'=> ucwords(strtolower('SILVANA CHIAVEGATTO')), 'email'=>'schiaveg@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('07964525808',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '18148777896', 'nome'=> ucwords(strtolower('SONIA APARECIDA DE ANDRADE CHUDZINSKI')), 'email'=>'sonia.andrade@butantan.gov.br','instituicao_vinculo'=>'Butantã', 'password'=> password_hash(substr('18148777896',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '22817805895', 'nome'=> ucwords(strtolower('SORAYA DA SILVA SANTOS')), 'email'=>'soraya.ssantos@yahoo.com.br','instituicao_vinculo'=>'IQ', 'password'=> password_hash(substr('22817805895',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '38418410310', 'nome'=> ucwords(strtolower('TÉRCIO ELYAN AZEVEDO MARTINS')), 'email'=>'terciomartins@me.com','instituicao_vinculo'=>'UNIP', 'password'=> password_hash(substr('38418410310',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '30408351810', 'nome'=> ucwords(strtolower('THALITA BOLDRIN ZANONI')), 'email'=>'thalitaz@fcfrp.usp.br','instituicao_vinculo'=>'FCF', 'password'=> password_hash(substr('30408351810',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '19507937889', 'nome'=> ucwords(strtolower('VAGNER ROBERTO ANTUNES')), 'email'=>'antunes@icb.usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('19507937889',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '13029823890', 'nome'=> ucwords(strtolower('VERIDIANA MUNFORD')), 'email'=>'vmunford@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('13029823890',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '63468492804', 'nome'=> ucwords(strtolower('VILMA LEYTON')), 'email'=>'vileyton@usp.br','instituicao_vinculo'=>'FM', 'password'=> password_hash(substr('63468492804',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '05838132671', 'nome'=> ucwords(strtolower('VINICIUS CALDEIRA QUINTÃO')), 'email'=>'Vinicius.quintao@hc.fm.usp.br','instituicao_vinculo'=>'FM', 'password'=> password_hash(substr('05838132671',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '15065627878', 'nome'=> ucwords(strtolower('VIVIANE MAIMONI GONÇALVES')), 'email'=>'viviane.goncalves@butantan.gov.br','instituicao_vinculo'=>'Butantã', 'password'=> password_hash(substr('15065627878',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );
        DB::table('orientadores')->insert(['CPF' => '37077250814', 'nome'=> ucwords(strtolower('WESLEY NOGUEIRA BRANDÃO')), 'email'=>'wesleybrandao@usp.br','instituicao_vinculo'=>'ICB', 'password'=> password_hash(substr('37077250814',0,8), PASSWORD_DEFAULT), 'externo' => 1, 'aprovado' => 1, 'created_at' => date_create('now'), 'updated_at' => date_create('now') ] );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
